services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: quiz123
      POSTGRES_DB: quizdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quizdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: quiz123

volumes:
  postgres-data: